### ISSUE TITLE
Can't resolve androidmads.library.qrgenearator.QRGContents

### ISSUE THREAD

**Issue by SaharAbbasiFard** [androidmads/QRGenerator#62]
After update to 1.0.4 version I can't use your library. I can't import  androidmads.library.qrgenearator.QRGContents and android studio can't even find androidmads anywhere of project. I have searched for it in all scopes.

**Comment by auspicious99** [comment]
Same here. I used 1.0.3 for some time, and perhaps 1.0.1 even earlier.

Now, with the new gradle model, I was happy to see in your README that you support the following in settings.gradle

```
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven(url = "https://jitpack.io")
    }
}
```

I used this except that I had to put the jitpack line as `maven { url "https://jitpack.io" }` as gradle sync was giving an error otherwise.

Then gradle sync was fine, but can't import androidmads.library.qrgenearator.QRGContents when building the app.

Android studio jellyfish (2023.3.1 patch 2), gradle 8.4.2, java 17

**Comment by tomjod** [comment]
I have the same error, I can't import androidmads.library.qrgenearator.QRGContents, I can't find it anywhere of the project. I waste a lot of time trying to make it work.

**Comment by 2blane** [comment]
I spent a good hour on this. Do what @auspicious99 did, also make sure to remove the below from build.gradle Project if it is there. Then, you can go to jitpack.io and plug in this Github repo's url and it will tell you how to install it in your project. This has been huge for other dependencies that were failing as well. It just grabs from the Github account instead of using some repository that may or may not have the code uploaded.
'''
all projects {
    repositories {...}
}
'''

**Comment by SaNu-hIT** [comment]
Same issue for me , anyone got a breakthrough ?

**Comment by androidmads** [comment]
can you please recheck the readme and download the latest gradle library, try the same.

**Comment by harisashraf1** [comment]
Anyone found any solution?

**Comment by logicog** [comment]
I have the same issue, I configure gradle as in the README. During gradle sync, the QRGenerator sources are downloaded and I believe also built, but the import does not find them during build.

**Comment by sTunahan** [comment]
solution implementation `‘androidmads.library.qrgenearator:QRGenearator:1.0.3’ - instead of 1.0.4. `
`implementation ‘com.github.androidmads:QRGenerator:1.0.1’. `

**Comment by androidmads** [comment]
Use the library using implementation ‘com.github.androidmads:QRGenerator:1.0.5’.
